#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by T4.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using Sitecore.Data;

namespace Shared.SC.Feature.Login
{
    [CLSCompliant(false)]
    public static class Templates
    {
        public static class LoginSettings
        {
            public static readonly ID Id = new ID("f3ee8318-8957-426d-9e21-7d477cb6ab9a");
        
            public struct Fields
            {
                public static readonly ID PostLoginRedirect = new ID("a3e6b64b-b27d-41df-8094-ffdfca8070a0");
                public const string PostLoginRedirectFieldName = "Post Login Redirect";
            }
        }
    }
}
